### ISSUE TITLE
Create logo for Cognizance

### ISSUE THREAD

**Issue by joshi1983** [joshi1983/cognizance#1]
The logo being should have a circle around the silhouette of the profile of a head.

One image Phil liked included a source image that was too restricted by copyright so I made the following image from my head that can be used instead:
[josh_head.zip](https://github.com/joshi1983/cognizance/files/1867886/josh_head.zip)

**Comment by joshi1983** [comment]
@super8989 when do you think you can make a new version of the logo based on the recent feedback from Phil?

**Comment by super8989** [comment]
I made some different iterations using the logo from Josh. 
I couldn't really combine mine with Josh's head logo to produce anything good or worthwhile so I took a different approach. 

[Logo2.pdf](https://github.com/joshi1983/cognizance/files/1876545/Logo2.pdf)

**Comment by joshi1983** [comment]
I zipped an SVG version of the logo that Phil pointed out in here:
[cognizance_logo.zip](https://github.com/joshi1983/cognizance/files/1887601/cognizance_logo.zip)


I also replaced the silhouette of the head with one of mine so we don't risk as much with copyright infringement.

The SVG isn't perfect but my efforts to clean up the SVG were reaching a point of diminishing returns.  Some minor remaining problems include:
-  an unwanted black line between the purple and white parts of the big circle
- the yellow path outlines more of the brain than necessary.
- some of the lines in the yellow shape are not very smooth

**Comment by joshi1983** [comment]
I'll close this issue since we very much have a logo.  The remaining improvements are unlikely to be made before the Hacking Health event.

**Comment by joshi1983** [comment]
It is funny how the logo resembles Pacman's logo.  That was just a coincidence but not sure if we like that.  On the one hand, we don't have any pacman-like aspect to the tests.  On the other, we do have game-like tests and pacman is a very recognizable game.

https://simple.wikipedia.org/wiki/Pac-Man
