### ISSUE TITLE
Create an installable Progressive Web App(PWA) version of the Cognizance application

### ISSUE THREAD

**Issue by joshi1983** [joshi1983/cognizance#8]
This may not be complete for the Hacking Health event but PWA will be easier to install and maintain than a native Android application so we ultimately want one.

**Comment by joshi1983** [comment]
@jaykrz I assigned this to you since you were eager to take it on.

**Comment by joshi1983** [comment]
@jaykrz if you're PWA installation requires a logo, the logo is at: http://polla.bhstudents.net/cognizance/images/logo.svg

It uses my head to make it obvious that we didn't use any copyrighted material.

**Comment by joshi1983** [comment]
Your changes were merged.  I adjusted the theme colours and the url to /cognizance.  I also made a change that tries to make scalable no for PWA but keep it available for most of the pages.

Can you test if the installation works well?  

I installed using "Add to Home screen" on my phone but I don't see the logo while loading the app.  Pinch to scale doesn't scale which is a little evidence for it using the manifest file to install it.

**Comment by jaykrz** [comment]
Ya there appears to be something wrong with the logo. The logo also doesn't show as an icon on the home screen.

![inshot_20180409_214722872](https://user-images.githubusercontent.com/6231555/38531849-069be74c-3c40-11e8-939f-f24bdb2e6d3f.jpg)

 See the bottom one is shows the logo.

**Comment by joshi1983** [comment]
@jaykrz your problem with the logo looks complete so I'm closing this.

**Comment by joshi1983** [comment]
@jaykrz is it difficult to have the back button work in the home screen app?  @super8989 thinks it would make it easier to navigate in an iphone.

In my Android phone I can access the back feature if I swipe it down.  On the Android, I kind of like it.

**Comment by jaykrz** [comment]
I don't think it's as simple on iOS as it is on Android. Android natively has that back button while an iPhone does not.

This is one of the qwerks that people have to deal with when making an app work across both mobile platforms. We will have to incorporate a way to go back directly in html to get this kind of functionality in iOS as far as I know.
