### ISSUE TITLE
Create page for explaining how to install the Android app

### ISSUE THREAD

**Issue by joshi1983** [joshi1983/cognizance#9]
Amazon has a page here that explains how to install their Android app without using Google Play.  We want to use the same format:
https://www.amazon.ca/gp/feature.html?ie=UTF8&docId=1001119741

This task would break down to the following:
- [x] Create a new file named something like android-install.php.
- [x] Use the header footer PHP functions like other pages.
- [x] Include a link to 'downloads/app-release.apk' like the index.php has.
- [x] Add instructions for adding the app to a mobile device's desktop
- [x] Test for various viewport widths and heights that mobile devices would typically use and optimize 
multiple layouts for them.
- [x] Update index.php to link to the new android-install.php instead of directly to the apk file.
- [x] Detect if using Android device and show a warning message if the user is of an IOS device

**Comment by joshi1983** [comment]
@super8989 can you test this with your iPhone?

1. Navigate to http://polla.bhstudents.net/cognizance/install.php with your iPhone.
1. Do you see a message just under method 2 warning that the Android APK won't work for an iPhone?

This image shows where the message should appear only for IOS devices like your iPhone:
![image](https://user-images.githubusercontent.com/11838191/39047707-dca71f70-4468-11e8-8e36-94d6544ff030.png)

**Comment by super8989** [comment]
Error message shows up 
![ba5c0dd1-bd20-41a3-baab-b9a9567bb720](https://user-images.githubusercontent.com/33507285/39078281-62ff6132-44d6-11e8-9f1e-cd0fadd8c0bb.jpeg)

**Comment by joshi1983** [comment]
Thanks for testing, Sam.  I'm closing because everything I wanted to do with this task is complete.
